120 pieq line model
CRESYM/colib0.github.io pull request #126
Opened 2024-05-14 08:50 UTC by Carlos-Alegre

Pull request for the pi-equivalent line model

2024-05-24 07:59 UTC, matoubongrain requested changes
complete the cp and fdline variables, equations, and parameters part.

2024-05-28 13:26 UTC, matoubongrain approved these changes

2024-05-30 10:13 UTC, GJCRESYM commented on pages/models/lines/piLine.md
> +| OpenIPSL | [Link](https://github.com/OpenIPSL/OpenIPSL/blob/master/OpenIPSL/Electrical/Branches/PwLine.mohttps://github.com/OpenIPSL/OpenIPSL/blob/master/OpenIPSL/Electrical/Branches/PwLine.mo ) |
OpenIPSL- Link is not working.

2024-05-30 10:15 UTC, Carlos-Alegre commented on pages/models/lines/piLine.md
> +| OpenIPSL | [Link](https://github.com/OpenIPSL/OpenIPSL/blob/master/OpenIPSL/Electrical/Branches/PwLine.mohttps://github.com/OpenIPSL/OpenIPSL/blob/master/OpenIPSL/Electrical/Branches/PwLine.mo ) |
Link duplicated, corrected

2024-05-30 16:02 UTC, merged