130 review 4 vsc benchmark case
CRESYM/colib0.github.io pull request #149
Opened 2024-05-30 15:57 UTC by matoubongrain

2024-05-30 16:23 UTC, GJCRESYM requested changes

2024-05-30 16:23 UTC, GJCRESYM commented on pages/testCases/converterDrivenStability/4VSCSystem/index.md
> +| |  R ($$\Omega/km$$) |  X ($$\Omega/km$$) | $$\omega *\frac{C}{2}$$ ($$\nu S/km$$)| Snom ($$MVA$$)  |
Table heading - Line Cable is missing

2024-05-30 16:23 UTC, GJCRESYM commented on pages/testCases/converterDrivenStability/4VSCSystem/index.md
> +A single dynamic model is used for all four [converters](/pages/models/generations/Sources/VSC/RMSGridFollowingVSC/index.md) (though with a control variant for WP1 with respect to the other VSCs).
Link to converters is not working

2024-05-31 08:00 UTC, matoubongrain commented on pages/testCases/converterDrivenStability/4VSCSystem/index.md
> +A single dynamic model is used for all four [converters](/pages/models/generations/Sources/VSC/RMSGridFollowingVSC/index.md) (though with a control variant for WP1 with respect to the other VSCs).
link updated

2024-05-31 08:17 UTC, GJCRESYM approved these changes

2024-05-31 08:21 UTC, merged