PR for 180- Phasor GFM VSC model
CRESYM/colib0.github.io pull request #185
Opened 2024-07-22 11:23 UTC by Carlos-Alegre

Pull request for issue #180 Phasor Grid Forming VSC Model

2024-07-24 15:00 UTC, GJCRESYM requested changes

2024-07-24 15:00 UTC, GJCRESYM commented on pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
I believe this is a new folder for PhasorGridFormingVSC. I am not sure why its showing comparison. It should be a new file. Similarly, other svg files as well.

2024-07-24 15:00 UTC, GJCRESYM commented on pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
Can you verify whether you pull the latest changes from main before creating this? I am missing EMT Grid Forming here
![image](https://github.com/user-attachments/assets/1fa29b13-7e1c-4899-a6ac-c013cd6114d4)

2024-07-25 08:23 UTC, Carlos-Alegre commented on pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
This is due to using a previous page as a template. I did an intermediate commit when I published it to the Github to save some changes prior to the pull request, that's why there is a comparison.  Similarly for the SVGs files, since some of them are shared between both models.
The EMT model was still not approved when this branch was created, I will merge the main branch now that it is up

2024-07-25 09:49 UTC, GJCRESYM requested changes

2024-07-25 09:49 UTC, GJCRESYM commented on pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
> +     alt="EMT GF VSC scheme"
Should it refer to Phasor Grid Forming VSC scheme?

2024-07-25 09:49 UTC, GJCRESYM commented on pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
> +Figure 1: EMT Grid Forming VSC scheme <a href="#1">[1]</a>
Figure name: Should it refer to Phasor Gris Forming VSC scheme?

2024-07-25 09:49 UTC, GJCRESYM commented on pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
> +Figure 2: Synchronization Loop Diagram
Leave one space between figure and description

2024-07-25 09:49 UTC, GJCRESYM commented on pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
> +where $$J$$ is the inertia of the machine, $$\omega$$ is the angular frequency of the machine, $$P_r^*$$ is the virtual input power (which emulates the mechanical power), and $$P_e$$ is the electrica
Please confirm: [Grid Following model](../EMTGridFollowingVSC/)
EMT or Phasor?

2024-07-25 09:49 UTC, GJCRESYM commented on pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
> +The voltage control is used to determine the current setpoints that will be used to control the converter. The tuning of this control has been done using the Internal Model Control method (IMC) [[8]]
Internal Model Control method (IMC) [[8]](#8),

Did you mean 7?

2024-07-25 11:19 UTC, GJCRESYM approved these changes

2024-07-25 14:26 UTC, merged