PR for Point to Point HVDC model
CRESYM/colib0.github.io pull request #194
Opened 2024-08-01 08:25 UTC by Carlos-Alegre

Pull request for the ID-190 Point to Point EMT HVDC model

2024-08-01 11:48 UTC, GJCRESYM requested changes

2024-08-01 11:48 UTC, GJCRESYM commented on pages/models/HVDC/EMTVSC/index.md
> +As all the EMTs model, it is not suitable for low-frequency studies, such as power flow or dynamic stability studies, as its computational cost is high, and the time step cannot be reduced too much w
Typo: "losing" instead of loosing

2024-08-01 11:48 UTC, GJCRESYM commented on pages/models/HVDC/EMTVSC/index.md
> +This model has been successfully implemented in :
Table is not formatted properly

2024-08-01 14:46 UTC, Carlos-Alegre commented on pages/models/HVDC/EMTVSC/index.md
> +This model has been successfully implemented in :
Corrected

2024-08-01 14:46 UTC, Carlos-Alegre commented on pages/models/HVDC/EMTVSC/index.md
> +As all the EMTs model, it is not suitable for low-frequency studies, such as power flow or dynamic stability studies, as its computational cost is high, and the time step cannot be reduced too much w
Corrected

2024-08-02 08:00 UTC, GJCRESYM approved these changes

2024-08-02 08:00 UTC, merged