Add induction motor models
CRESYM/colib0.github.io pull request #215
Opened 2024-08-19 08:45 UTC by FredericSabot

Closes #200

2024-11-05 13:17 UTC, Lampros-Cresym reviewed
Thank you Frederic for contributing to Colib. 
Do you think it would be possible to add indicative parameters to the tables?

Apart from that both two entries are well described and ready to be approved.

2024-11-06 10:00 UTC, Lampros-Cresym approved these changes

2024-11-07 12:33 UTC, GJCRESYM requested changes
@FredericSabot : Small changes to be implemented. Could you please have a look?

2024-11-07 12:33 UTC, GJCRESYM commented on pages/models/motors/SimpleMotor/index.md
> +reviewers:
```suggestion
reviewers: Lampros Papangelis (CRESYM)
```

2024-11-07 12:33 UTC, GJCRESYM commented on pages/models/motors/WECC_Motor/index.md
> +reviewers:
```suggestion
reviewers: Lampros Papangelis (CRESYM)
```

2024-11-07 12:33 UTC, GJCRESYM commented on pages/models/motors/WECC_Motor/index.md
> +Motors are a particular kind of load that can account for a large share of the total load especially in industrialised countries. Adequate representation of motors is important, especially in short-t
```suggestion
Motors are a particular kind of load that can account for a large share of the total load especially in industrialised countries. Adequate representation of motors is important, especially in short-term voltage stability studies as motors can cause fault-induced delayed voltage recovery [[1]](#1).
```

2024-11-07 12:33 UTC, GJCRESYM commented on pages/models/motors/WECC_Motor/index.md
> +<a id="1">[1]</a> PowerWorld. "Load Characteristic MOTORW", https://www.powerworld.com/WebHelp/Content/TransientModels_HTML/Load%20Characteristic%20MOTORW.htm, Last accessed 12/08/2024
Please remove last accessed date: 

![image](https://github.com/user-attachments/assets/f106c335-c392-4fcf-bd54-b990b7cd3046)

2024-11-12 14:17 UTC, Lampros-Cresym approved these changes

2024-11-15 08:16 UTC, GJCRESYM approved these changes

2024-11-15 08:52 UTC, merged