Issue 233: Changes on EMT STATCOM model
CRESYM/colib0.github.io pull request #244
Opened 2024-10-23 14:51 UTC by Carlos-Alegre

Pull request for the changes in the EMT STATCOM model.

2024-11-05 12:59 UTC, Lampros-Cresym commented on pages/models/CompensationDevices/STATCOM/index.md
> +The following table shows possible values for the parameters of the controllers using the tunning proposed:
```suggestion
The following table shows possible values for the parameters of the controllers using the tuning proposed:
```

2024-11-05 13:00 UTC, Lampros-Cresym commented on pages/models/CompensationDevices/STATCOM/index.md
> +| $$V_{peak}$$ | $$2500$$ | V |
please check if Vpeak appears anywhere.

2024-11-05 13:01 UTC, Lampros-Cresym commented on pages/models/CompensationDevices/STATCOM/index.md
> +## Parameter tunning
```suggestion
## Parameter tuning 
```

2024-11-05 13:01 UTC, Lampros-Cresym approved these changes
minor changes.

2024-11-07 08:32 UTC, Carlos-Alegre commented on pages/models/CompensationDevices/STATCOM/index.md
> +| $$V_{peak}$$ | $$2500$$ | V |
Chenged to Vdc

2024-11-15 08:32 UTC, GJCRESYM approved these changes

2024-11-15 16:16 UTC, Lampros-Cresym approved these changes

2024-11-15 16:55 UTC, Lampros-Cresym requested changes
Figures not appearing correctly. Probably a path problem?

2024-11-18 09:05 UTC, Carlos-Alegre commented
> Figures not appearing correctly. Probably a path problem?

Hmmm I can see all of the figures. Can you post a screenshot?

2024-11-22 14:54 UTC, Lampros-Cresym approved these changes

2024-11-22 16:03 UTC, merged