Issue 247: GFM-GFOL DC link test case
CRESYM/colib0.github.io pull request #248
Opened 2024-10-24 10:54 UTC by Carlos-Alegre

Pull request for the GFM-GFOL DC link test case

2024-11-15 16:54 UTC, Lampros-Cresym requested changes
Same here, there is a problem with the figures

2024-12-13 08:22 UTC, GJCRESYM commented
@Carlos-Alegre : Is it ready for review? I still see it in change request mode. Could you please confirm?

2024-12-16 15:47 UTC, Carlos-Alegre commented
> @Carlos-Alegre : Is it ready for review? I still see it in change request mode. Could you please confirm?

@GJCRESYM We may have found the issue with the initial transient, I will keep you updated during this week

2024-12-19 13:12 UTC, Lampros-Cresym commented
> > > @Carlos-Alegre : Is it ready for review? I still see it in change request mode. Could you please confirm?
> > 
> > 
> > @GJCRESYM We may have found the issue with the initial transient, I will keep you updated during this week
> 
> @GJCRESYM @Lampros-Cresym Transient part of the simulation is now improved. There was an issue with the initialization of the currents of the inductors, which was causing some controllers to use an initial measurement of current that did not correspond to the steady-state conditions

That makes sense. There is still some transient remaining. Maybe a capacitor voltage used in a voltage controller? If not evident, I guess we can leave with it...

2025-01-28 18:15 UTC, Lampros-Cresym commented
Hi @Carlos-Alegre is there any update on this test case? Should we consider it as finished?

2025-02-06 13:42 UTC, Lampros-Cresym approved these changes

2025-02-06 16:12 UTC, GJCRESYM approved these changes

2025-02-06 16:15 UTC, merged