Diagram paths corrected
CRESYM/colib0.github.io pull request #249
Opened 2024-10-30 08:28 UTC by ErwanGuichard49

closes [#169](https://github.com/CRESYM/colib0.github.io/issues/169)

2024-11-15 16:51 UTC, Lampros-Cresym requested changes
Hi Erwan,

1. Is it possible to add indicative parameters to the tables?
2. Is it possible to increase the fond of the text (parameters,etc.) in the block diagrams? It appears too small in my case.

2024-11-18 09:10 UTC, ErwanGuichard49 commented
> Hi Erwan,
> 
>     1. Is it possible to add indicative parameters to the tables?
> 
>     2. Is it possible to increase the fond of the text (parameters,etc.) in the block diagrams? It appears too small in my case.

Dear Lampros,

Your comments pertain to the branch [236](https://github.com/CRESYM/colib0.github.io/pull/243) (https://github.com/CRESYM/colib0.github.io/pull/243).

2024-11-18 09:35 UTC, ErwanGuichard49 commented
The present pull request deals only with the paths to the block diagrams, which are currently not visible on the website.

2024-11-22 15:11 UTC, Lampros-Cresym approved these changes

2024-11-22 16:06 UTC, merged