Issue 229 - Phasor GFM VSC corrections
CRESYM/colib0.github.io pull request #251
Opened 2024-11-07 11:48 UTC by Carlos-Alegre

Pull request for the Phasor GFM VSC corrections - Issue 229

2024-11-15 16:53 UTC, Lampros-Cresym requested changes
Here again, there is a problem with the figures .

2024-11-18 09:12 UTC, Carlos-Alegre commented
> Hi Carlos. Please check the paths of the figures. There also seems to be a problem with one of the equations. ![image](https://private-user-images.githubusercontent.com/180533733/386690280-c6899c98-f0d8-4cdf-b804-4f436e762cc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjEyNjQsIm5iZiI6MTczMTkyMDk2NCwicGF0aCI6Ii8xODA1MzM3MzMvMzg2NjkwMjgwLWM2ODk5Yzk4LWYwZDgtNGNkZi1iODA0LTRmNDM2ZTc2MmNjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwOTA5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWQxZWQzNjAwY2Y4YzcyNTU3NmRiZDlmYTYzMDBmNDgwZjQwZDA3MjkwY2E4MGM1MTQxYzExZTc1ZmU0YTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bp768-5frlf1Hc2lo63iARAMZLnx3IFO8D4ARV1bePI)


To me it looks okay. The equation box that is showing in your screenshot reminds me to some Markdown interfaces that are not completely compatible. That might be the issue.
 
![image](https://github.com/user-attachments/assets/e2aa365e-d4d2-416c-bbbb-a26e76eb2841)

2024-11-22 14:56 UTC, GJCRESYM approved these changes

2024-11-22 15:05 UTC, Lampros-Cresym approved these changes

2024-11-22 16:05 UTC, merged