add wt type 3
CRESYM/colib0.github.io pull request #264
Opened 2024-12-20 12:21 UTC by martinscripts

see #62

2025-02-27 12:10 UTC, Lampros-Cresym approved these changes

2025-03-17 13:39 UTC, GJCRESYM requested changes

2025-03-17 14:59 UTC, martinscripts commented on pages/models/generations/wind/iec_wt_type3/index.md
> +![](WindType3_files/figure-commonmark/fig-lookup-table-omega-pref-output-1.png)
thanks for pointing this out, I added the file and fixed the path

2025-03-18 16:16 UTC, GJCRESYM requested changes

2025-03-19 08:42 UTC, martinscripts commented on pages/models/generations/wind/iec_wt_type3/index.md
> +<a href="#sec-torque-pi" class="quarto-xref">Section 4.1.1</a>) is the
Yes, see below 

![grafik](https://github.com/user-attachments/assets/dc32f34b-99c1-45ee-8a41-a63184680096)

2025-03-19 08:43 UTC, martinscripts commented on pages/models/generations/wind/iec_wt_type3/index.md
> +<a href="#sec-wt-p-params" class="quarto-xref">Section 4.1.3</a>).
yes

![grafik](https://github.com/user-attachments/assets/19f339a0-744e-4725-824b-388192009524)

2025-03-20 10:07 UTC, GJCRESYM approved these changes

2025-03-20 10:09 UTC, merged